"%dev":
  quarkus:
    http:
      port: 8081
amqp-host: ${AMQP_HOST:localhost}
amqp-port: ${AMQP_PORT:5672}
amqp-username: ${AMQP_USERNAME:quarkus}
amqp-password: ${AMQP_PASSWORD:quarkus}
kafka:
  bootstrap:
    servers:
      - localhost:9092
quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER:app_color}
    password: ${DB_PASSWORD:app_color}
    jdbc:
      url: jdbc:postgresql://${DB_HOST:localhost:15432}/${DB_DATABASE:app_color}
      max-size: 8
      min-size: 2
mp:
  messaging:
    incoming:
      jms-new-color-channel:
        connector: smallrye-amqp
        durable: true
        use-anonymous-sender: false
    outgoing:
      kafka-new-color-created-channel:
        connector: smallrye-kafka
        topic: kafka-new-color-created-channel
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer